const CONFIG = {
  RECEIPTS_LABEL: "Receipts/Auto",
  PROCESSED_LABEL: "Receipts/Processed",
  SHEET_NAME: "Expenses",
  RULES_SHEET_NAME: "Rules",
  EXPENSES_ROOT_FOLDER_ID: "PASTE_YOUR_DRIVE_FOLDER_ID_HERE",
  MIN_ATTACHMENT_BYTES: 10 * 1024,
};